err.burn:
	== 1

$ burn err.burn
	* stderr
		Expected expression.
		in err.burn on line 1
			== 1
			^
	* exit status nonzero

err.burn:
	1 ==

$ burn err.burn
	* stderr
		Expected expression.
		in err.burn on line 1
			1 ==
			    ^
	* exit status nonzero

err.burn:
	==

$ burn err.burn
	* stderr
		Expected expression.
		in err.burn on line 1
			==
			^
	* exit status nonzero

err.burn:
	1 == 1 == 1

$ burn err.burn
	* stderr
		Expected newline.
		in err.burn on line 1
			1 == 1 == 1
			       ^
	* exit status nonzero
